# Generated by Django 5.2.5 on 2025-08-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_us', models.CharField(max_length=10, unique=True)),
                ('contrasena_us', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10, unique=True)),
                ('nombre_est', models.CharField(max_length=30)),
                ('apellido_est', models.CharField(max_length=30)),
                ('fechanac_est', models.DateField()),
                ('sexo_est', models.CharField(max_length=1)),
                ('correo_est', models.EmailField(max_length=254, unique=True)),
                ('telefono_est', models.CharField(max_length=15, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
